version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.0
    steps:
      - checkout
      - run: composer install
      - run: composer lint
      - run: composer test

workflows:
  build_and_test:
    jobs:
      - build
